import { writeFile } from "node:fs/promises";
import path from "node:path";

import { generateEmbeddings } from "../src/lib/rag/embedding";
import { fewShotQueries, tableDetails } from "./ragDataEmbeddingData";

// cli= export token --> npx tsx prisma/generateLocalRagEmbeddings

type TableDetailsEntry = {
  id: string;
  name: string;
  description: string;
  embedding: number[];
};

type FewShotEntry = {
  id: string;
  query: string;
  answer: string;
  embedding: number[];
};

async function main() {
  console.log("🔧 [local RAG] Generating local embeddings for table details and few-shot examples...");

  const tableEntries = Object.entries(tableDetails);
  const fewShotEntries = Object.entries(fewShotQueries);

  // Prepare texts to embed
  const tableTexts = tableEntries.map(([name, description]) => {
    // Include the logical table name in the text to help lexical matching
    return `${name}\n\n${description}`;
  });
  const fewShotTexts = fewShotEntries.map(
    ([question, guidance]) => `${question}\n\n${guidance}`
  );

  const allTexts = [...tableTexts, ...fewShotTexts];

  console.log(`🔧 [local RAG] Embedding ${allTexts.length} items...`);

  // Reuse the existing embedding generator so dimensions/model stay in sync
  const allEmbeddings: number[][] = [];
  for (const text of allTexts) {
    const embedding = await generateEmbeddings(text);
    allEmbeddings.push(embedding);
  }

  const tableEmbeddings = allEmbeddings.slice(0, tableEntries.length);
  const fewShotEmbeddings = allEmbeddings.slice(tableEntries.length);

  const tableResults: TableDetailsEntry[] = tableEntries.map(
    ([name, description], idx) => ({
      id: name,
      name,
      description,
      embedding: tableEmbeddings[idx],
    })
  );

  const fewShotResults: FewShotEntry[] = fewShotEntries.map(
    ([question, answer], idx) => ({
      id: `fs-${idx}`,
      query: question,
      answer,
      embedding: fewShotEmbeddings[idx],
    })
  );

  const outputPath = path.join(
    process.cwd(),
    "src",
    "lib",
    "rag",
    "localRagEmbeddings.generated.ts"
  );

  const header = `/* eslint-disable */
// This file is auto-generated by prisma/generateLocalRagEmbeddings.ts
// Do NOT edit this file manually. Instead, update prisma/ragDataEmbeddingData.ts
// and re-run the generator script.

export type TableDetailEmbedding = {
  id: string;
  name: string;
  description: string;
  embedding: number[];
};

export type FewShotEmbedding = {
  id: string;
  query: string;
  answer: string;
  embedding: number[];
};

`;

  const content =
    header +
    `export const tableDetailEmbeddings: TableDetailEmbedding[] = ${JSON.stringify(
      tableResults,
      null,
      2
    )} as const;\n\n` +
    `export const fewShotEmbeddings: FewShotEmbedding[] = ${JSON.stringify(
      fewShotResults,
      null,
      2
    )} as const;\n`;

  await writeFile(outputPath, content, "utf8");

  console.log(`✅ [local RAG] Wrote local embeddings to: ${outputPath}`);
}

main().catch((err) => {
  console.error("❌ [local RAG] Failed to generate local embeddings:", err);
  process.exit(1);
});


