import prisma from "@/lib/prisma/client";

async function main() {
  // Clear existing data in correct FK order
  await prisma.rentRollUnit.deleteMany();
  await prisma.capex.deleteMany();
  await prisma.opex.deleteMany();
  await prisma.asset.deleteMany();

  // Seed example assets with related capex, opex and rent roll units
  await prisma.asset.create({
    data: {
      name: "Sunset Apartments",
      address: "123 Sunset Blvd",
      city: "Los Angeles",
      country: "USA",
      capex: {
        create: [
          {
            asset_name: "Sunset Apartments",
            capex_year: 2024,
            common_areas_actuals: 50000,
            units_renovations_actuals: 80000,
            elevator_maintnance_actuals: 15000,
            roof_maintnance_actuals: 20000,
            fire_safety_actuals: 10000,
            outdoor_area_actuals: 12000,
            total_capex_actuals: 187000,
            common_areas_budget: 60000,
            units_renovations_budget: 90000,
            elevator_maintnance_budget: 15000,
            roof_maintnance_budget: 25000,
            fire_safety_budget: 12000,
            outdoor_area_budget: 15000,
            total_capex_budget: 219000,
          },
        ],
      },
      opex: {
        create: [
          {
            asset_name: "Sunset Apartments",
            opex_year: 2024,
            actual_delinquency: 5000,
            actual_property_management_fee: 30000,
            actual_leasing_fee: 8000,
            actual_property_taxes: 60000,
            actual_refuse_collection: 7000,
            actual_insurance: 12000,
            actual_cleaning: 15000,
            actual_facility_management: 18000,
            actual_service_subscriptions: 6000,
            actual_common_consumption: 9000,
            actual_home_owner_association: 4000,
            actuals_total_opex: 176000,
            budget_delinquency: 4000,
            budget_property_management_fee: 28000,
            budget_leasing_fee: 7000,
            budget_property_taxes: 62000,
            budget_refuse_collection: 6500,
            budget_insurance: 11000,
            budget_cleaning: 14000,
            budget_facility_management: 17000,
            budget_service_subscriptions: 5500,
            budget_common_consumption: 8500,
            budget_home_owner_association: 3500,
            budget_total_opex: 170000,
          },
        ],
      },
      rentRoll: {
        create: [
          {
            unit_id: 101,
            property_build_year: 1998,
            property_name: "Sunset Apartments",
            unit_address: "123 Sunset Blvd, Apt 101",
            unit_zipcode: "90001",
            utilites_cost: 150,
            unit_type: "2BR",
            size_sqm: 70,
            rooms_amount: 3,
            bedrooms_amount: 2,
            bathrooms_amount: 1,
            rent_current_gri: 2200,
            rent_budget_tri: 2300,
            lease_start: "2024-01-01",
            lease_end: "2024-12-31",
            tenant_name1: "Alice Johnson",
            tenant_name2: "Bob Johnson",
            unit_door: 1,
            unit_floor: 1,
            tenant_number1: 1234567890,
            tenant_number2: 1987654321,
            units_status: "occupied",
            tenant_mail1: "alice@example.com",
            tenant_mail2: "bob@example.com",
          },
          {
            unit_id: 102,
            property_build_year: 1998,
            property_name: "Sunset Apartments",
            unit_address: "123 Sunset Blvd, Apt 102",
            unit_zipcode: "90001",
            utilites_cost: 140,
            unit_type: "1BR",
            size_sqm: 55,
            rooms_amount: 2,
            bedrooms_amount: 1,
            bathrooms_amount: 1,
            rent_current_gri: 1700,
            rent_budget_tri: 1800,
            lease_start: "2024-02-01",
            lease_end: null,
            tenant_name1: "Charlie Lee",
            tenant_name2: "",
            unit_door: 2,
            unit_floor: 1,
            tenant_number1: 1112223333,
            tenant_number2: 0,
            units_status: "occupied",
            tenant_mail1: "charlie@example.com",
            tenant_mail2: "",
          },
          {
            unit_id: 103,
            property_build_year: 1998,
            property_name: "Sunset Apartments",
            unit_address: "123 Sunset Blvd, Apt 201",
            unit_zipcode: "90001",
            utilites_cost: 160,
            unit_type: "3BR",
            size_sqm: 85,
            rooms_amount: 4,
            bedrooms_amount: 3,
            bathrooms_amount: 2,
            rent_current_gri: 2600,
            rent_budget_tri: 2700,
            lease_start: "2023-09-01",
            lease_end: "2025-08-31",
            tenant_name1: "David Kim",
            tenant_name2: "Eva Kim",
            unit_door: 3,
            unit_floor: 2,
            tenant_number1: 222333444,
            tenant_number2: 0,
            units_status: "occupied",
            tenant_mail1: "david.kim@example.com",
            tenant_mail2: "",
          },
          {
            unit_id: 104,
            property_build_year: 1998,
            property_name: "Sunset Apartments",
            unit_address: "123 Sunset Blvd, Apt 202",
            unit_zipcode: "90001",
            utilites_cost: 130,
            unit_type: "Studio",
            size_sqm: 40,
            rooms_amount: 1,
            bedrooms_amount: 0,
            bathrooms_amount: 1,
            rent_current_gri: 1400,
            rent_budget_tri: 1500,
            lease_start: "2024-04-01",
            lease_end: null,
            tenant_name1: "Vacant",
            tenant_name2: "",
            unit_door: 4,
            unit_floor: 2,
            tenant_number1: 0,
            tenant_number2: 0,
            units_status: "vacant",
            tenant_mail1: "",
            tenant_mail2: "",
          },
        ],
      },
    },
  });

  await prisma.asset.create({
    data: {
      name: "Harbor Offices",
      address: "500 Harbor Way",
      city: "San Francisco",
      country: "USA",
      capex: {
        create: [
          {
            asset_name: "Harbor Offices",
            capex_year: 2024,
            common_areas_actuals: 40000,
            units_renovations_actuals: 30000,
            elevator_maintnance_actuals: 10000,
            roof_maintnance_actuals: 15000,
            fire_safety_actuals: 8000,
            outdoor_area_actuals: 5000,
            total_capex_actuals: 108000,
            common_areas_budget: 45000,
            units_renovations_budget: 35000,
            elevator_maintnance_budget: 12000,
            roof_maintnance_budget: 16000,
            fire_safety_budget: 9000,
            outdoor_area_budget: 6000,
            total_capex_budget: 123000,
          },
        ],
      },
      opex: {
        create: [
          {
            asset_name: "Harbor Offices",
            opex_year: 2024,
            actual_delinquency: 3000,
            actual_property_management_fee: 25000,
            actual_leasing_fee: 6000,
            actual_property_taxes: 80000,
            actual_refuse_collection: 6000,
            actual_insurance: 15000,
            actual_cleaning: 20000,
            actual_facility_management: 22000,
            actual_service_subscriptions: 7000,
            actual_common_consumption: 10000,
            actual_home_owner_association: 5000,
            actuals_total_opex: 196000,
            budget_delinquency: 2500,
            budget_property_management_fee: 24000,
            budget_leasing_fee: 5500,
            budget_property_taxes: 82000,
            budget_refuse_collection: 5800,
            budget_insurance: 14000,
            budget_cleaning: 19000,
            budget_facility_management: 21000,
            budget_service_subscriptions: 6500,
            budget_common_consumption: 9500,
            budget_home_owner_association: 4500,
            budget_total_opex: 192000,
          },
        ],
      },
      rentRoll: {
        create: [
          {
            unit_id: 201,
            property_build_year: 2005,
            property_name: "Harbor Offices",
            unit_address: "500 Harbor Way, Suite 201",
            unit_zipcode: "94105",
            utilites_cost: 300,
            unit_type: "Office",
            size_sqm: 150,
            rooms_amount: 5,
            bedrooms_amount: 0,
            bathrooms_amount: 2,
            rent_current_gri: 6000,
            rent_budget_tri: 6200,
            lease_start: "2023-07-01",
            lease_end: "2026-06-30",
            tenant_name1: "Acme Corp",
            tenant_name2: "",
            unit_door: 1,
            unit_floor: 2,
            tenant_number1: 555123456,
            tenant_number2: 0,
            units_status: "occupied",
            tenant_mail1: "office@acme.com",
            tenant_mail2: "",
          },
          {
            unit_id: 202,
            property_build_year: 2005,
            property_name: "Harbor Offices",
            unit_address: "500 Harbor Way, Suite 202",
            unit_zipcode: "94105",
            utilites_cost: 280,
            unit_type: "Office",
            size_sqm: 130,
            rooms_amount: 4,
            bedrooms_amount: 0,
            bathrooms_amount: 2,
            rent_current_gri: 5500,
            rent_budget_tri: 5700,
            lease_start: "2024-03-01",
            lease_end: null,
            tenant_name1: "Beta LLC",
            tenant_name2: "",
            unit_door: 2,
            unit_floor: 2,
            tenant_number1: 555987654,
            tenant_number2: 0,
            units_status: "vacant",
            tenant_mail1: "contact@beta-llc.com",
            tenant_mail2: "",
          },
          {
            unit_id: 203,
            property_build_year: 2005,
            property_name: "Harbor Offices",
            unit_address: "500 Harbor Way, Suite 203",
            unit_zipcode: "94105",
            utilites_cost: 260,
            unit_type: "Office",
            size_sqm: 110,
            rooms_amount: 3,
            bedrooms_amount: 0,
            bathrooms_amount: 1,
            rent_current_gri: 5000,
            rent_budget_tri: 5200,
            lease_start: "2022-05-01",
            lease_end: "2025-04-30",
            tenant_name1: "Gamma Partners",
            tenant_name2: "",
            unit_door: 3,
            unit_floor: 2,
            tenant_number1: 333444555,
            tenant_number2: 0,
            units_status: "occupied",
            tenant_mail1: "admin@gammapartners.com",
            tenant_mail2: "",
          },
          {
            unit_id: 204,
            property_build_year: 2005,
            property_name: "Harbor Offices",
            unit_address: "500 Harbor Way, Suite 301",
            unit_zipcode: "94105",
            utilites_cost: 320,
            unit_type: "Office",
            size_sqm: 200,
            rooms_amount: 6,
            bedrooms_amount: 0,
            bathrooms_amount: 3,
            rent_current_gri: 7500,
            rent_budget_tri: 7700,
            lease_start: "2021-01-01",
            lease_end: null,
            tenant_name1: "Delta Ventures",
            tenant_name2: "",
            unit_door: 1,
            unit_floor: 3,
            tenant_number1: 444555666,
            tenant_number2: 0,
            units_status: "occupied",
            tenant_mail1: "contact@deltaventures.com",
            tenant_mail2: "",
          },
        ],
      },
    },
  });
}

main()
  .then(async () => {
    await prisma.$disconnect();
  })
  .catch(async (e) => {
    console.error(e);
    await prisma.$disconnect();
    process.exit(1);
  });


